-- Modelo relacional preparado para PostgreSQL / Supabase
create table people (
  id bigint generated by default as identity primary key,
  name text not null,
  biography text,
  roles text[] default '{}',
  photo_url text,
  created_at timestamptz default now()
);

create table films (
  id bigint generated by default as identity primary key,
  title text not null,
  year integer,
  duration_minutes integer,
  genre text,
  format text,
  synopsis text,
  poster_url text,
  media_url text,
  created_at timestamptz default now()
);

create table film_people (
  film_id bigint references films on delete cascade,
  person_id bigint references people on delete cascade,
  role text not null,
  primary key (film_id, person_id, role)
);

create type archive_record_type as enum ('press', 'interview', 'article');
create table archive_records (
  id bigint generated by default as identity primary key,
  record_type archive_record_type not null,
  title text not null,
  author text,
  source text,
  published_at date,
  format text,
  body text,
  file_url text,
  film_id bigint references films on delete set null,
  person_id bigint references people on delete set null,
  created_at timestamptz default now()
);

create table collections (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  cover_url text,
  created_at timestamptz default now()
);

create index films_search_idx on films using gin(to_tsvector('spanish', title || ' ' || coalesce(synopsis,'')));
create index people_search_idx on people using gin(to_tsvector('spanish', name || ' ' || coalesce(biography,'')));
create index archive_search_idx on archive_records using gin(to_tsvector('spanish', title || ' ' || coalesce(body,'')));

alter table films enable row level security;
alter table people enable row level security;
alter table archive_records enable row level security;
create policy "Public read films" on films for select using (true);
create policy "Public read people" on people for select using (true);
create policy "Public read archive" on archive_records for select using (true);
