import { BookOpen, FileText, Film, Mic2, UserRound } from 'lucide-react';

export const records = [
  { id: 1, type:'Película', slug:'peliculas', title:'Canto a la tierra', subtitle:'Sergio Trabucco', year:'1972', format:'Documental · 18 min · 16 mm', collection:'Memoria rural', color:'#d9ff43', image:'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=1400&q=88', description:'Un retrato íntimo de las comunidades campesinas del Valle del Limarí y de su relación con un territorio marcado por los ciclos del agua.' },
  { id: 2, type:'Película', slug:'peliculas', title:'Bajo el cielo de Ovalle', subtitle:'Elena Godoy', year:'1969', format:'Ficción · 74 min · 35 mm', collection:'Cine regional', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=88', description:'Una ficción coral recuperada que recorre las calles, los oficios y los encuentros de la ciudad a fines de los años sesenta.' },
  { id: 3, type:'Persona', slug:'personas', title:'Elena Godoy Araya', subtitle:'Directora · Guionista', year:'1941—2008', format:'6 obras vinculadas', collection:'Realizadoras del Limarí', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=900&q=88', description:'Pionera del cine regional, desarrolló una obra sensible en torno a la vida cotidiana y la memoria de las mujeres del Limarí.' },
  { id: 4, type:'Prensa', slug:'prensa', title:'Una sala para imaginar', subtitle:'Diario El Limarí', year:'1971', format:'Recorte · 2 páginas', collection:'Cineteca 1968—1977', color:'#ffdc72', image:'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1000&q=88', description:'Crónica sobre las primeras exhibiciones comunitarias y la formación de una audiencia cinematográfica local.' },
  { id: 5, type:'Entrevista', slug:'entrevistas', title:'Proyectar también era resistir', subtitle:'Marta Castillo', year:'2024', format:'Audio · 42 min', collection:'Memoria oral', color:'#d9ff43', image:'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1000&q=88', description:'Una conversación sobre los cineclubes, las funciones itinerantes y la experiencia colectiva de ver cine en Ovalle.' },
  { id: 6, type:'Artículo', slug:'articulos', title:'Imágenes que vuelven a casa', subtitle:'Camila Rojas M.', year:'2025', format:'Ensayo · 12 min lectura', collection:'Preservación', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1000&q=88', description:'Una reflexión sobre el valor de recuperar, digitalizar y hacer circular el patrimonio audiovisual de los territorios.' },
  { id: 7, type:'Película', slug:'peliculas', title:'Agua de los valles', subtitle:'Luis Cortés', year:'1984', format:'Documental · 31 min · Súper 8', collection:'Territorio', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1000&q=88', description:'Registro documental de los canales, cultivos y voces que construyen el paisaje del Limarí.' },
  { id: 8, type:'Persona', slug:'personas', title:'Manuel Peñafiel', subtitle:'Proyeccionista · Gestor', year:'1935—1998', format:'14 registros vinculados', collection:'Oficios del cine', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=88', description:'Proyeccionista y animador cultural, pieza fundamental de la circulación cinematográfica en la provincia.' },
  { id: 9, type:'Prensa', slug:'prensa', title:'El cine llega a las poblaciones', subtitle:'La Provincia', year:'1975', format:'Crónica · 1 página', collection:'Exhibición comunitaria', color:'#ffdc72', image:'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=1000&q=88', description:'Registro de las jornadas itinerantes que acercaron el cine a distintos sectores de la comuna.' },
  { id: 10, type:'Entrevista', slug:'entrevistas', title:'La luz detrás de la pantalla', subtitle:'Carlos Pizarro', year:'2023', format:'Video · 28 min', collection:'Oficios del cine', color:'#d9ff43', image:'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1000&q=88', description:'Testimonio sobre el oficio de proyeccionista y la vida cotidiana en las antiguas salas de Ovalle.' },
  { id: 11, type:'Artículo', slug:'articulos', title:'Geografías del cine nortino', subtitle:'Valentina Díaz', year:'2025', format:'Investigación · 18 min', collection:'Territorio', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1000&q=88', description:'Una lectura crítica de los paisajes, relatos y comunidades representados por el cine regional.' },
  { id: 12, type:'Película', slug:'peliculas', title:'Semillas de otoño', subtitle:'Rosa Alcayaga', year:'1978', format:'Documental · 22 min · 16 mm', collection:'Memoria rural', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=88', description:'Un recorrido por las labores de siembra y cosecha en los valles interiores, filmado a lo largo de una temporada agrícola completa.' },
  { id: 13, type:'Película', slug:'peliculas', title:'El tren del norte', subtitle:'Francisco Ibarra', year:'1965', format:'Ficción · 58 min · 35 mm', collection:'Cine regional', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1000&q=88', description:'La llegada del ferrocarril a la provincia narrada a través de tres familias que disputan el mismo andén.' },
  { id: 14, type:'Película', slug:'peliculas', title:'Voces del valle', subtitle:'Teresa Bahamondes', year:'1991', format:'Documental · 40 min · Súper 8', collection:'Territorio', color:'#ffdc72', image:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=88', description:'Testimonios de regantes y comuneros sobre el uso ancestral del agua en los canales del Limarí.' },
  { id: 15, type:'Película', slug:'peliculas', title:'Cosecha', subtitle:'Hernán Cortés', year:'1980', format:'Documental · 15 min · 16 mm', collection:'Memoria rural', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1000&q=88', description:'Un registro silencioso de la vendimia en los valles de Ovalle, filmado sin diálogos ni música.' },
  { id: 16, type:'Película', slug:'peliculas', title:'La sala vacía', subtitle:'Patricio Reyes', year:'2001', format:'Ficción · 12 min · Video', collection:'Cine regional', color:'#d9ff43', image:'https://images.unsplash.com/photo-1586899028174-e7098604235b?auto=format&fit=crop&w=1000&q=88', description:'Un proyeccionista recorre por última vez una sala de cine a punto de cerrar sus puertas.' },
  { id: 17, type:'Película', slug:'peliculas', title:'Ríos que hablan', subtitle:'Marisol Varas', year:'2015', format:'Documental · 26 min · Digital', collection:'Territorio', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1000&q=88', description:'Un ensayo visual sobre la sequía y la memoria del agua en las comunidades del interior.' },
  { id: 18, type:'Película', slug:'peliculas', title:'Encuentro en la plaza', subtitle:'Osvaldo Molina', year:'1954', format:'Ficción · 20 min · 16 mm', collection:'Cine regional', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=1000&q=88', description:'Una comedia costumbrista sobre las funciones de cine itinerante que llegaban a la plaza de Ovalle.' },
  { id: 19, type:'Persona', slug:'personas', title:'Rosa Alcayaga Vidal', subtitle:'Directora · Documentalista', year:'1944—2015', format:'5 obras vinculadas', collection:'Realizadoras del Limarí', color:'#ffdc72', image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=88', description:'Pionera del documental rural, registró durante décadas los oficios y paisajes agrícolas de la provincia.' },
  { id: 20, type:'Persona', slug:'personas', title:'Francisco Ibarra Soto', subtitle:'Director · Montajista', year:'1938—2010', format:'4 obras vinculadas', collection:'Cine regional', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=1000&q=88', description:'Formado en Santiago, volvió a Ovalle para retratar la llegada de la modernidad al valle del Limarí.' },
  { id: 21, type:'Persona', slug:'personas', title:'Teresa Bahamondes', subtitle:'Documentalista · Socióloga', year:'1960', format:'3 obras vinculadas', collection:'Territorio', color:'#d9ff43', image:'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1000&q=88', description:'Su trabajo cruza la etnografía y el cine para documentar los sistemas de riego tradicionales.' },
  { id: 22, type:'Persona', slug:'personas', title:'Hernán Cortés Villalobos', subtitle:'Camarógrafo · Fotógrafo', year:'1950—2019', format:'7 registros vinculados', collection:'Oficios del cine', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1000&q=88', description:'Camarógrafo autodidacta que documentó las labores agrícolas del Limarí durante más de treinta años.' },
  { id: 23, type:'Persona', slug:'personas', title:'Patricio Reyes', subtitle:'Proyeccionista · Gestor cultural', year:'1965', format:'6 registros vinculados', collection:'Oficios del cine', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1000&q=88', description:'Último proyeccionista del antiguo Cine Ovalle, hoy dedicado a la formación de nuevas audiencias.' },
  { id: 24, type:'Persona', slug:'personas', title:'Marisol Varas', subtitle:'Directora · Guionista', year:'1982', format:'2 obras vinculadas', collection:'Realizadoras del Limarí', color:'#ffdc72', image:'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1000&q=88', description:'Su cine ensayístico explora la relación entre territorio, memoria y crisis hídrica.' },
  { id: 25, type:'Persona', slug:'personas', title:'Osvaldo Molina', subtitle:'Director · Actor', year:'1925—1994', format:'3 obras vinculadas', collection:'Cine regional', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1000&q=88', description:'Figura fundacional del cine costumbrista de la provincia, actuó y dirigió en sus propias producciones.' },
  { id: 26, type:'Persona', slug:'personas', title:'Javier Muñoz Peña', subtitle:'Técnico de sonido', year:'1955—2016', format:'9 registros vinculados', collection:'Oficios del cine', color:'#d9ff43', image:'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=1000&q=88', description:'Responsable del registro sonoro de decenas de entrevistas y documentales del archivo regional.' },
  { id: 27, type:'Prensa', slug:'prensa', title:'Nueva sala en el centro', subtitle:'Diario El Limarí', year:'1968', format:'Recorte · 1 página', collection:'Cineteca 1968—1977', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1000&q=88', description:'Anuncio de la inauguración de la primera sala estable dedicada a la exhibición de cine regional.' },
  { id: 28, type:'Prensa', slug:'prensa', title:'Polémica por censura de película local', subtitle:'La Provincia', year:'1973', format:'Crónica · 2 páginas', collection:'Cineteca 1968—1977', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1000&q=88', description:'Cobertura del debate público generado por la prohibición temporal de un documental sobre huelgas agrícolas.' },
  { id: 29, type:'Prensa', slug:'prensa', title:'El cine como memoria del valle', subtitle:'Diario El Limarí', year:'1985', format:'Reportaje · 3 páginas', collection:'Exhibición comunitaria', color:'#ffdc72', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=88', description:'Entrevista a realizadores locales sobre la importancia de conservar los registros audiovisuales de la provincia.' },
  { id: 30, type:'Prensa', slug:'prensa', title:'Se pierde archivo fílmico en incendio', subtitle:'La Provincia', year:'1990', format:'Noticia · 1 página', collection:'Preservación', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1000&q=88', description:'Crónica sobre la pérdida parcial de un fondo audiovisual privado y el llamado a resguardar el patrimonio local.' },
  { id: 31, type:'Prensa', slug:'prensa', title:'Festival itinerante recorre la provincia', subtitle:'Diario El Limarí', year:'1998', format:'Crónica · 2 páginas', collection:'Exhibición comunitaria', color:'#d9ff43', image:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=88', description:'Registro del recorrido de un festival de cine por localidades rurales del Limarí durante un mes.' },
  { id: 32, type:'Prensa', slug:'prensa', title:'Restauración digital del archivo Peñafiel', subtitle:'La Provincia', year:'2022', format:'Reportaje · 2 páginas', collection:'Preservación', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1000&q=88', description:'Cobertura del proceso de digitalización de un fondo fílmico donado por la familia de un antiguo proyeccionista.' },
  { id: 33, type:'Prensa', slug:'prensa', title:'Vecinos piden reabrir el cine municipal', subtitle:'Diario El Limarí', year:'2010', format:'Carta · 1 página', collection:'Exhibición comunitaria', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1586899028174-e7098604235b?auto=format&fit=crop&w=1000&q=88', description:'Petición ciudadana para recuperar el uso cultural de un edificio histórico cerrado desde los años noventa.' },
  { id: 34, type:'Prensa', slug:'prensa', title:'La Cineteca cumple medio siglo', subtitle:'La Provincia', year:'2018', format:'Reportaje · 4 páginas', collection:'Cineteca 1968—1977', color:'#ffdc72', image:'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1000&q=88', description:'Balance de cincuenta años de exhibición, formación y archivo cinematográfico en la comuna.' },
  { id: 35, type:'Entrevista', slug:'entrevistas', title:'Filmar sin permiso', subtitle:'Teresa Bahamondes', year:'2020', format:'Audio · 35 min', collection:'Memoria oral', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=1000&q=88', description:'La realizadora recuerda las dificultades para registrar comunidades rurales durante los años de dictadura.' },
  { id: 36, type:'Entrevista', slug:'entrevistas', title:'El sonido también cuenta la historia', subtitle:'Javier Muñoz', year:'2019', format:'Audio · 30 min', collection:'Oficios del cine', color:'#d9ff43', image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1000&q=88', description:'Un técnico de sonido repasa décadas de grabaciones de campo en la provincia del Limarí.' },
  { id: 37, type:'Entrevista', slug:'entrevistas', title:'Actuar frente a la cámara por primera vez', subtitle:'Osvaldo Molina (archivo)', year:'1988', format:'Audio · 20 min', collection:'Memoria oral', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=1000&q=88', description:'Grabación histórica donde el actor recuerda sus inicios en el cine costumbrista local.' },
  { id: 38, type:'Entrevista', slug:'entrevistas', title:'Restaurar es también interpretar', subtitle:'Equipo de digitalización', year:'2023', format:'Video · 33 min', collection:'Preservación', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1000&q=88', description:'Conversación sobre las decisiones técnicas y éticas involucradas en la restauración de películas antiguas.' },
  { id: 39, type:'Entrevista', slug:'entrevistas', title:'La cámara como testigo', subtitle:'Hernán Cortés', year:'2021', format:'Video · 26 min', collection:'Oficios del cine', color:'#ffdc72', image:'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1000&q=88', description:'El camarógrafo reflexiona sobre su rol como testigo silencioso de las transformaciones del valle.' },
  { id: 40, type:'Entrevista', slug:'entrevistas', title:'Ser mujer detrás de la cámara', subtitle:'Marisol Varas', year:'2024', format:'Audio · 38 min', collection:'Realizadoras del Limarí', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1000&q=88', description:'Una conversación sobre los desafíos de dirigir cine documental en un territorio rural.' },
  { id: 41, type:'Entrevista', slug:'entrevistas', title:'El último rollo', subtitle:'Patricio Reyes', year:'2022', format:'Video · 24 min', collection:'Oficios del cine', color:'#d9ff43', image:'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1000&q=88', description:'El antiguo proyeccionista narra el cierre de la última sala de cine tradicional en la comuna.' },
  { id: 42, type:'Entrevista', slug:'entrevistas', title:'Memoria del agua', subtitle:'Comuneros de Río Hurtado', year:'2017', format:'Audio · 45 min', collection:'Memoria oral', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1000&q=88', description:'Testimonios colectivos sobre los cambios en el régimen de lluvias y su efecto en la vida cotidiana.' },
  { id: 43, type:'Artículo', slug:'articulos', title:'Cartografías del archivo audiovisual', subtitle:'Diego Fernández', year:'2022', format:'Ensayo · 15 min lectura', collection:'Preservación', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=1000&q=88', description:'Un mapeo de los fondos fílmicos dispersos en la provincia y los desafíos para su catalogación conjunta.' },
  { id: 44, type:'Artículo', slug:'articulos', title:'Cine y ruralidad en el norte chico', subtitle:'Camila Rojas M.', year:'2023', format:'Investigación · 20 min lectura', collection:'Territorio', color:'#ffdc72', image:'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1000&q=88', description:'Un análisis de las representaciones del mundo rural en el cine documental producido en la región.' },
  { id: 45, type:'Artículo', slug:'articulos', title:'Mujeres detrás y delante de la cámara', subtitle:'Valentina Díaz', year:'2024', format:'Ensayo · 14 min lectura', collection:'Realizadoras del Limarí', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1000&q=88', description:'Una revisión del rol de las realizadoras en la historia del cine regional, muchas veces invisibilizado.' },
  { id: 46, type:'Artículo', slug:'articulos', title:'El oficio de proyeccionista, entre la técnica y la comunidad', subtitle:'Diego Fernández', year:'2021', format:'Investigación · 16 min lectura', collection:'Oficios del cine', color:'#d9ff43', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=88', description:'Una historia social de los proyeccionistas que sostuvieron la exhibición de cine en la provincia.' },
  { id: 47, type:'Artículo', slug:'articulos', title:'Archivos en riesgo: patrimonio fílmico no catalogado', subtitle:'Camila Rojas M.', year:'2020', format:'Reportaje · 10 min lectura', collection:'Preservación', color:'#8ee6c4', image:'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1000&q=88', description:'Un llamado de atención sobre los fondos audiovisuales privados amenazados por el deterioro material.' },
  { id: 48, type:'Artículo', slug:'articulos', title:'La prensa local como fuente audiovisual', subtitle:'Valentina Díaz', year:'2022', format:'Ensayo · 12 min lectura', collection:'Cineteca 1968—1977', color:'#ffc3d8', image:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=88', description:'Una reflexión sobre cómo los recortes de prensa complementan la comprensión del archivo fílmico regional.' },
  { id: 49, type:'Artículo', slug:'articulos', title:'Formas de mirar el agua en el cine del Limarí', subtitle:'Diego Fernández', year:'2025', format:'Investigación · 18 min lectura', collection:'Territorio', color:'#ffdc72', image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1000&q=88', description:'Un recorrido por las distintas maneras en que el cine regional ha representado la crisis hídrica.' },
  { id: 50, type:'Artículo', slug:'articulos', title:'Cineclubes y formación de públicos', subtitle:'Camila Rojas M.', year:'2019', format:'Ensayo · 13 min lectura', collection:'Exhibición comunitaria', color:'#b8c8ff', image:'https://images.unsplash.com/photo-1586899028174-e7098604235b?auto=format&fit=crop&w=1000&q=88', description:'Una historia de los cineclubes comunitarios que educaron a generaciones de espectadores en la provincia.' }
];

export const sections = [
  { label:'Películas', slug:'peliculas', type:'Película', icon:Film, desc:'Obras, registros y piezas audiovisuales.' },
  { label:'Personas', slug:'personas', type:'Persona', icon:UserRound, desc:'Realizadores, intérpretes y oficios.' },
  { label:'Prensa', slug:'prensa', type:'Prensa', icon:FileText, desc:'Recortes y documentos digitalizados.' },
  { label:'Entrevistas', slug:'entrevistas', type:'Entrevista', icon:Mic2, desc:'Relatos en texto, audio y video.' },
  { label:'Artículos', slug:'articulos', type:'Artículo', icon:BookOpen, desc:'Investigación, ensayos y crítica.' }
];

export const recordExtras = {
  1:{credits:[['Fotografía','María Cortés'],['Montaje','Jorge Tapia'],['Producción','Taller Limarí']],relations:[3,4,5],locations:['Valle del Limarí','Monte Patria','Río Hurtado'],mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4',gallery:['https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85']},
  2:{credits:[['Guion','Elena Godoy'],['Cámara','Raúl Fuentes'],['Música','Enrique Soto']],relations:[3,4,8],locations:['Ovalle'],mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4',gallery:['https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1200&q=85']},
  3:{credits:[['Rol principal','Dirección'],['Archivo','Fondo Elena Godoy'],['Donación','Familia Godoy']],relations:[2,4,6],location:'Ovalle',mediaType:'image',gallery:['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=85']},
  4:{credits:[['Medio','Diario El Limarí'],['Fondo','Manuel Peñafiel'],['Páginas','2']],relations:[1,2,8],location:'Ovalle',mediaType:'document'},
  5:{credits:[['Entrevista','Camila Rojas'],['Sonido','Javier Muñoz'],['Duración','42 minutos']],relations:[1,3,8],location:'Monte Patria',mediaType:'audio',media:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'},
  6:{credits:[['Edición','Revista Norte Audiovisual'],['Extensión','12 minutos'],['Licencia','CC BY-NC']],relations:[1,2,3],location:'Ovalle',mediaType:'text'},
  7:{credits:[['Dirección','Luis Cortés'],['Formato','Súper 8'],['Restauración','2024']],relations:[1,9,11],locations:['Río Hurtado','Monte Patria'],mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4'},
  8:{credits:[['Oficio','Proyeccionista'],['Actividad','1958—1994'],['Fondo','Familia Peñafiel']],relations:[2,4,5],location:'Monte Patria',mediaType:'image'},
  9:{credits:[['Medio','La Provincia'],['Fecha','15 de junio de 1975'],['Sección','Cultura']],relations:[2,4,8],location:'Ovalle',mediaType:'document'},
  10:{credits:[['Realización','Cineteca de Ovalle'],['Cámara','Ana Rojas'],['Duración','28 minutos']],relations:[5,8,9],location:'Ovalle',mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4'},
  11:{credits:[['Revista','Cuadernos del Norte'],['Volumen','N.º 12'],['Páginas','34—49']],relations:[1,6,7],location:'Provincia del Limarí',mediaType:'text'},
  12:{credits:[['Dirección','Rosa Alcayaga'],['Cámara','Hernán Cortés'],['Sonido','Javier Muñoz']],relations:[19,22,26],locations:['Monte Patria'],mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4'},
  13:{credits:[['Dirección','Francisco Ibarra'],['Guion','Francisco Ibarra'],['Producción','Estudios Limarí']],relations:[20,18,25],locations:['Ovalle'],mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4'},
  14:{credits:[['Dirección','Teresa Bahamondes'],['Investigación','Teresa Bahamondes'],['Sonido','Javier Muñoz']],relations:[21,35,26],locations:['Río Hurtado','Ovalle'],mediaType:'video'},
  15:{credits:[['Dirección','Hernán Cortés'],['Cámara','Hernán Cortés'],['Montaje','Rosa Alcayaga']],relations:[22,12,19],locations:['Punitaqui'],mediaType:'video'},
  16:{credits:[['Dirección','Patricio Reyes'],['Guion','Patricio Reyes'],['Actuación','Osvaldo Molina']],relations:[23,41,25],locations:['Ovalle'],mediaType:'video'},
  17:{credits:[['Dirección','Marisol Varas'],['Cámara','Hernán Cortés'],['Montaje','Marisol Varas']],relations:[24,40,22],locations:['Río Hurtado'],mediaType:'video'},
  18:{credits:[['Dirección','Osvaldo Molina'],['Actuación','Osvaldo Molina'],['Producción','Cine Club Ovalle']],relations:[25,37,13],locations:['Ovalle'],mediaType:'video'},
  19:{credits:[['Rol principal','Dirección documental'],['Archivo','Fondo Rosa Alcayaga'],['Donación','Familia Alcayaga']],relations:[12,15,24],location:'Monte Patria',mediaType:'image'},
  20:{credits:[['Rol principal','Dirección · Montaje'],['Archivo','Fondo Francisco Ibarra'],['Formación','Escuela de cine, Santiago']],relations:[13,18,25],location:'Ovalle',mediaType:'image'},
  21:{credits:[['Rol principal','Documental · Investigación'],['Disciplina','Sociología'],['Línea de trabajo','Sistemas de riego']],relations:[14,35,42],location:'Río Hurtado',mediaType:'image'},
  22:{credits:[['Oficio','Camarógrafo'],['Actividad','1978—2010'],['Fondo','Archivo personal']],relations:[15,17,39],location:'Punitaqui',mediaType:'image'},
  23:{credits:[['Oficio','Proyeccionista'],['Actividad','1985—2020'],['Sala','Cine Ovalle']],relations:[16,41,8],location:'Ovalle',mediaType:'image'},
  24:{credits:[['Rol principal','Dirección · Guion'],['Formación','Cine documental'],['Línea de trabajo','Crisis hídrica']],relations:[17,40,21],location:'Ovalle',mediaType:'image'},
  25:{credits:[['Rol principal','Dirección · Actuación'],['Archivo','Fondo Osvaldo Molina'],['Actividad','1948—1990']],relations:[18,37,20],location:'Ovalle',mediaType:'image'},
  26:{credits:[['Oficio','Técnico de sonido'],['Actividad','1975—2016'],['Registros','Más de 40 grabaciones de campo']],relations:[5,14,36],location:'Ovalle',mediaType:'image'},
  27:{credits:[['Medio','Diario El Limarí'],['Fecha','3 de agosto de 1968'],['Sección','Cultura']],relations:[34,18,23],location:'Ovalle',mediaType:'document'},
  28:{credits:[['Medio','La Provincia'],['Fecha','12 de mayo de 1973'],['Sección','Actualidad']],relations:[9,34,25],location:'Ovalle',mediaType:'document'},
  29:{credits:[['Medio','Diario El Limarí'],['Fecha','20 de octubre de 1985'],['Sección','Reportajes']],relations:[20,25,44],location:'Ovalle',mediaType:'document'},
  30:{credits:[['Medio','La Provincia'],['Fecha','7 de febrero de 1990'],['Sección','Sucesos']],relations:[47,32,8],location:'Combarbalá',mediaType:'document'},
  31:{credits:[['Medio','Diario El Limarí'],['Fecha','14 de marzo de 1998'],['Sección','Cultura']],relations:[9,50,4],location:'Punitaqui',mediaType:'document'},
  32:{credits:[['Medio','La Provincia'],['Fecha','2 de septiembre de 2022'],['Sección','Cultura']],relations:[8,47,43],location:'Monte Patria',mediaType:'document'},
  33:{credits:[['Medio','Diario El Limarí'],['Fecha','19 de junio de 2010'],['Sección','Cartas']],relations:[16,23,50],location:'Ovalle',mediaType:'document'},
  34:{credits:[['Medio','La Provincia'],['Fecha','11 de noviembre de 2018'],['Sección','Reportajes']],relations:[27,4,50],location:'Ovalle',mediaType:'document'},
  35:{credits:[['Entrevista','Camila Rojas'],['Sonido','Javier Muñoz'],['Duración','35 minutos']],relations:[21,14,42],location:'Río Hurtado',mediaType:'audio',media:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'},
  36:{credits:[['Entrevista','Diego Fernández'],['Sonido','Registro propio'],['Duración','30 minutos']],relations:[26,5,10],location:'Ovalle',mediaType:'audio',media:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'},
  37:{credits:[['Entrevista','Archivo oral CDO'],['Año de registro','1988'],['Duración','20 minutos']],relations:[25,18,13],location:'Ovalle',mediaType:'audio',media:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'},
  38:{credits:[['Entrevista','Camila Rojas'],['Participantes','Equipo de digitalización CDO'],['Duración','33 minutos']],relations:[32,47,8],location:'Ovalle',mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4'},
  39:{credits:[['Entrevista','Valentina Díaz'],['Cámara','Registro propio'],['Duración','26 minutos']],relations:[22,15,17],location:'Punitaqui',mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Mt_Baker.mp4'},
  40:{credits:[['Entrevista','Camila Rojas'],['Sonido','Javier Muñoz'],['Duración','38 minutos']],relations:[24,17,45],location:'Ovalle',mediaType:'audio',media:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'},
  41:{credits:[['Entrevista','Diego Fernández'],['Cámara','Registro propio'],['Duración','24 minutos']],relations:[23,16,33],location:'Ovalle',mediaType:'video',media:'https://storage.googleapis.com/coverr-main/mp4/Footboys.mp4'},
  42:{credits:[['Entrevista','Teresa Bahamondes'],['Participantes','Comuneros de Río Hurtado'],['Duración','45 minutos']],relations:[14,21,35],location:'Río Hurtado',mediaType:'audio',media:'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'},
  43:{credits:[['Edición','Revista Norte Audiovisual'],['Extensión','15 minutos'],['Licencia','CC BY-NC']],relations:[47,32,6],location:'Ovalle',mediaType:'text'},
  44:{credits:[['Edición','Cuadernos del Norte'],['Extensión','20 minutos'],['Licencia','CC BY-NC']],relations:[14,29,7],location:'Río Hurtado',mediaType:'text'},
  45:{credits:[['Edición','Revista Norte Audiovisual'],['Extensión','14 minutos'],['Licencia','CC BY-NC']],relations:[24,19,40],location:'Ovalle',mediaType:'text'},
  46:{credits:[['Edición','Cuadernos del Norte'],['Extensión','16 minutos'],['Licencia','CC BY-NC']],relations:[23,8,41],location:'Ovalle',mediaType:'text'},
  47:{credits:[['Edición','Revista Norte Audiovisual'],['Extensión','10 minutos'],['Licencia','CC BY-NC']],relations:[30,32,43],location:'Combarbalá',mediaType:'text'},
  48:{credits:[['Edición','Cuadernos del Norte'],['Extensión','12 minutos'],['Licencia','CC BY-NC']],relations:[4,9,34],location:'Ovalle',mediaType:'text'},
  49:{credits:[['Edición','Revista Norte Audiovisual'],['Extensión','18 minutos'],['Licencia','CC BY-NC']],relations:[17,14,42],location:'Río Hurtado',mediaType:'text'},
  50:{credits:[['Edición','Cuadernos del Norte'],['Extensión','13 minutos'],['Licencia','CC BY-NC']],relations:[31,33,4],location:'Ovalle',mediaType:'text'}
};

export const collections = [
  {slug:'memoria-rural',title:'Memoria rural',years:'1968—1989',description:'Paisajes, trabajos y comunidades campesinas registrados por el cine regional.',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1400&q=88',color:'#d9ff43'},
  {slug:'oficios-del-cine',title:'Oficios del cine',years:'1958—2004',description:'Las personas detrás de la cámara, la proyección, el sonido y la circulación.',image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1400&q=88',color:'#8ee6c4'},
  {slug:'cineteca-1968-1977',title:'Cineteca 1968—1977',years:'1968—1977',description:'Una década de exhibiciones, encuentros y resistencia cultural en Ovalle.',image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1400&q=88',color:'#ffdc72'},
  {slug:'realizadoras',title:'Realizadoras del Limarí',years:'1969—2026',description:'Películas, documentos y testimonios de mujeres creadoras del territorio.',image:'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=1400&q=88',color:'#ffc3d8'}
];

export const timelineEvents = [
  {year:'1938',title:'El cine llega a la plaza',text:'Las funciones itinerantes transforman temporalmente el espacio público de Ovalle.',type:'Exhibición',image:'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1000&q=85'},
  {year:'1968',title:'Nace la Cineteca',text:'Comienza un proyecto de exhibición, conversación y formación cinematográfica.',type:'Hito',image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1000&q=85'},
  {year:'1972',title:'Canto a la tierra',text:'Se filma uno de los registros documentales más significativos del archivo.',type:'Película',image:records[0].image},
  {year:'1977',title:'Resistencia cultural',text:'La comunidad conserva los documentos y películas de una década fundamental.',type:'Memoria',image:'https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1000&q=85'},
  {year:'2024',title:'Digitalización',text:'Comienza la restauración y catalogación sistemática de los fondos audiovisuales.',type:'Preservación',image:'https://images.unsplash.com/photo-1586899028174-e7098604235b?auto=format&fit=crop&w=1000&q=85'},
  {year:'2026',title:'Archivo abierto',text:'El patrimonio regresa a la comunidad mediante una nueva plataforma digital.',type:'Acceso',image:'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&w=1000&q=85'}
];

export const locations = [
  {id:1,name:'Ovalle',lat:-30.6011,lon:-71.1990,text:'Centro de exhibición, producción y documentación del archivo.'},
  {id:2,name:'Monte Patria',lat:-30.6940,lon:-70.9577,text:'Memorias orales, funciones itinerantes y registros comunitarios.'},
  {id:3,name:'Río Hurtado',lat:-30.2730,lon:-70.6910,text:'Paisajes documentales y patrimonio rural del norte del Limarí.'},
  {id:4,name:'Combarbalá',lat:-31.1790,lon:-71.0020,text:'Relatos locales y circuitos históricos de exhibición.'},
  {id:5,name:'Punitaqui',lat:-30.8330,lon:-71.2650,text:'Colecciones familiares, fotografías y prensa histórica.'}
];

// Portada: cada línea del título va en `title` (separadas por \n); `em` es el remate en cursiva
export const heroSlides = [
  { eyebrow:'CINE · TERRITORIO · MEMORIA', title:'Un archivo\nque vuelve a', em:'mirarnos.', desc:'La memoria audiovisual de Ovalle, abierta para todas y todos.', image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1900&q=90', alt:'Rodaje cinematográfico', link:'/archivo' },
  { eyebrow:'OBRAS AUDIOVISUALES', title:'Películas que\ncuentan el', em:'territorio.', desc:'Ficción y documental de casi ocho décadas de cine regional.', image:'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=1900&q=90', alt:'Paisaje del Valle del Limarí', link:'/peliculas' },
  { eyebrow:'VOCES Y OFICIOS', title:'Las personas\ndetrás de', em:'cada imagen.', desc:'Directoras, actores, técnicos y gestores del cine del Limarí.', image:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1900&q=90', alt:'Retrato', link:'/personas' },
  { eyebrow:'RECORRIDOS CURATORIALES', title:'Historias\nreunidas por', em:'temas.', desc:'Explora colecciones temáticas dentro del archivo.', image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1900&q=90', alt:'Colecciones del archivo', link:'/colecciones' }
];

// Ajustes generales del sitio
export const site = { featuredId: 1 };

// Textos del inicio. Usa *asteriscos* para la cursiva y saltos de línea donde quieras cortar.
// {años} se reemplaza por los años de historia del archivo.
export const homeContent = {
  heroEdition:'ARCHIVO DIGITAL\nEDICIÓN 2026', heroCta:'Explorar',
  searchKicker:'ENCUENTRA ALGO', searchTitle:'Más de mil historias esperan\nser encontradas.', searchPlaceholder:'Título, persona, año, tema…', searchAdvanced:'Búsqueda avanzada',
  statsKicker:'EL ARCHIVO EN CIFRAS', statsTitle:'Más de {años} años de cine del Limarí, *contados uno a uno.*', statsText:'Cada número es una historia rescatada: películas restauradas, voces que vuelven a escucharse y documentos que regresan a manos de la comunidad.',
  stats:[
    {label:'Películas',hint:'Ficción y documental restaurados'},
    {label:'Personas',hint:'Quienes filmaron, actuaron y proyectaron'},
    {label:'Documentos de prensa',hint:'Recortes, crónicas y programas'},
    {label:'Entrevistas',hint:'Memoria oral en audio y video'},
    {label:'Artículos',hint:'Investigación y crítica'},
    {label:'Colecciones',hint:'Recorridos curatoriales'},
    {label:'Comunas',hint:'Territorios del Limarí'},
    {label:'Registros en total',hint:'Todo el archivo, abierto'}
  ],
  portalLabel:'ENTRAR AL ARCHIVO', portalTitle:'Cinco puertas.\n*Infinitas conexiones.*', portalText:'Cada área vive ahora en su propia página, con filtros y contenidos específicos para encontrar lo que buscas más rápido.',
  discoveryLabel:'OTRAS FORMAS DE EXPLORAR', discoveryTitle:'El archivo desde\notras perspectivas.',
  tiles:[
    {kicker:'RECORRIDOS TEMÁTICOS',title:'Colecciones',text:'Historias reunidas por temas, épocas y comunidades.'},
    {kicker:'HISTORIA AUDIOVISUAL',title:'Línea de tiempo',text:'Recorre los hitos cinematográficos del territorio.'},
    {kicker:'GEOGRAFÍA DEL ARCHIVO',title:'Mapa territorial',text:'Descubre registros conectados con cada localidad.'},
    {kicker:'MEMORIA INSTITUCIONAL',title:'La Cineteca',text:'Conoce nuestra historia, misión y trabajo patrimonial.'}
  ],
  spotlightLabel:'PIEZA DESTACADA', spotlightTag:'Digitalización 4K', spotlightCta:'Abrir ficha', spotlightImage:'',
  latestLabel:'HALLAZGOS RECIENTES', latestTitle:'Recién catalogado', latestLink:'Ver todo el archivo', latestIds:[],
  manifestoText:'Preservar una imagen es devolverle\nal territorio una parte de su *memoria.*', manifestoSign:'CINETECA DE OVALLE', manifestoSub:'DESDE 1968 · REGIÓN DE COQUIMBO',
  footerTitle:'El archivo\nsigue *creciendo.*', footerExplore:'EXPLORAR', footerConnect:'CONECTAR',
  footerLinks:['Colecciones','Línea de tiempo','Mapa del archivo','Instagram','Contacto'],
  footerInstagram:'https://www.instagram.com/cinetecadeovalle/', footerEmail:'cinetecadeovalle@gmail.com', footerCopy:'© 2026 CINETECA DE OVALLE', footerPlace:'OVALLE · COQUIMBO · CHILE', footerTop:'INICIO ↑',
  hidden:[]
};

// Colores de toda la app. `palette` son los colores de etiquetas de fichas y colecciones.
export const theme = { acid:'#d9ff43', forest:'#123c2f', black:'#101210', paper:'#f2f0e9', palette:['#d9ff43','#8ee6c4','#ffc3d8','#ffdc72','#b8c8ff'] };
